# Generated by Django 3.2 on 2022-07-14 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('item_id', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory/item')),
                ('model_number', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField()),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apicrud.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apicrud.category')),
            ],
        ),
    ]
